version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    command: npm start
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - .:/home/node
      - node_modules:/home/node/node_modules
    depends_on:
      - db

  db:
    image: postgis/postgis:11-3.1-alpine
    volumes:
      - ./db-init.sh:/docker-entrypoint-initdb.d/init.sh
      - pg-data:/var/lib/postgresql/data
    user: postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

volumes:
  node_modules:
  pg-data:
