name: Node.js CI/CD

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 22
      uses: actions/setup-node@v2
      with:
        node-version: 22.x
    - run: npm ci
  cd:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy using ssh
      uses: D3rHase/ssh-command-action@latest
      env:
        PROJECT_PATH: ${{ secrets.PROJECT_PATH }}
        BRANCH: ${{ secrets.DEVELOPMENT_BRANCH }}
      with:
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        user: ${{ secrets.USER }}
        private_key: ${{ secrets.PRIVATE_KEY }}
        
        command: |
          echo 'Hello world!'
          cd $PROJECT_PATH
          git pull origin $BRANCH
          git status
          make provision
          make app
