name: Node.js CI/CD

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 22
      uses: actions/setup-node@v2
      with:
        node-version: 22.x
    - run: npm ci
  cd:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      env:
        PROJECT_PATH: ${{ secrets.PROJECT_PATH }}
        BRANCH: ${{ secrets.DEVELOP_BRANCH }}
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_SSH_KEY }}
        port: 22
        
        script: |
          cd $PROJECT_PATH
          git pull origin $BRANCH
          git status
          make provision
          make app
